# Red Neuronal Multicapa

Una red neuronal multicapa tiene capas ocultas entre la entrada y la salida. A este tipo de red también se le conoce como perceptrón multicapa (MLP por sus siglas en inglés de multilayer perceptron)

En este ejercicio crearemos una red neuronal multicapa usando numpy.

INSTRUCCIONES: Completa el código faltante.

@juan1rving

In [ ]:
#De La Huerta Avalos Gerardo Cristóbal
#2021630243
#6BM1

In [1]:
# Importamos paquetes
import numpy as np

np.random.seed(42)

In [2]:
# Funciones necesarias
def sigmoid(x):
    """
    Función sigmoide
    """
    return 1/(1+np.exp(-x))

## Definamos la arquitectura de la red

<img src="files/test1.png">

In [3]:
# TODO: Especifica el tamaño de las capas de acuerdo al diagrama.
N_input = 4
N_hidden = 3
N_out = 2


## Definir los pesos

Recordemos que los pesos ahora los representamos con matrices y utilizaremos el producton de la siguiente forma:

$$
h = XW
$$

tal que,


$$W = \begin{bmatrix}
w_{1,1} & w_{1,2}
 \\
w_{2,1} & w_{2,2}
 \\
w_{3,1} & w_{3,2}
 \\
\end{bmatrix}$$

donde los renglones se relacionan con las entradas y las columnas con los nodos intermedios. Y las entradas son

$$ X = \begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix} $$

Como herramienta usaremos:

> numpy.random.normal(loc=0.0, scale=1.0, size=None)

TODO: construye a contrinuación matrices con valores aleatorios para la matriz de pesos entre la entrada y la oculta y para la oculta y la salida.

In [9]:
#TODO: Completa el código faltante

mean = 0
stdev = 0.1

W_input_to_hidden = np.random.normal(loc=mean, scale=stdev, size=(N_input, N_hidden))

print(W_input_to_hidden)

W_hidden_out = np.random.normal(loc=mean, scale=stdev, size=(N_hidden, N_out))

print(W_hidden_out)

X = np.random.normal(loc=mean, scale=stdev, size=(N_input))

print(X)


[[-0.1478522  -0.07198442 -0.04606388]
 [ 0.10571222  0.03436183 -0.17630402]
 [ 0.0324084  -0.03850823 -0.0676922 ]
 [ 0.06116763  0.10309995  0.09312801]]
[[-0.08392175 -0.03092124]
 [ 0.03312634  0.09755451]
 [-0.04791742 -0.0185659 ]]
[-0.1106335  -0.11962066  0.08125258  0.135624  ]


## Calcular la salida

Recordemos de la lección que

$$ h = X W $$

$$ y = f(H) $$

In [10]:
# TODO: Producto punto
input_to_hidden = np.dot(X, W_input_to_hidden)

print(input_to_hidden)

out_of_hidden = []

for input in input_to_hidden:

    out_of_hidden.append(sigmoid(input))

print("salida de la capa oculta: ", out_of_hidden)

# TODO: Producto punto
input_to_out = np.dot(out_of_hidden, W_hidden_out)

out_of_network = []

for input in input_to_out:

    out_of_network.append(sigmoid(input))

print("salida de la red: ", out_of_network)


[0.0146411  0.01470744 0.03331604]
salida de la capa oculta:  [0.503660210714892, 0.5036767934101238, 0.5083282393445185]
salida de la red:  [0.48751738008089396, 0.5060308517677542]


Como resultado debes de ver la salida de la red como un vector de dos elementos.
